### ISSUE TITLE
Suggestion for reorganization

### ISSUE THREAD

**Issue by rt2zz** [mattotodd/react-native-addressbook-ios#2]
Many thanks for your work on this. I ended up recreating the module from scratch but copy and pasting most of your implementation code: https://github.com/rt2zz/react-native-addressbook

There were a few things I wanted to change:
- Just the library, no demo project
- Make API feel more akin to react-native core API's
- Make module naming more akin to other react-native modules

Let me know what you think. If you like the changes I can rebase it against your code and make a PR.

**Comment by rt2zz** [comment]
Moving forward with react-native-addressbook for now. Let me know if you want to reconcile the code in the future. Thanks!

**Comment by mattotodd** [comment]
Sorry Zack,  just saw this comment now.  

About your comments.   
- Any particular reason to get rid of the demo project?  I thought it helps to show a working example to get started? 
- In terms of making the API more akin to react-native core,  agreed.
- Renaming the module to RCTAddressBook ?  Fine with that

Also, about renaming actual contact attributes, I was trying to be in line with WC# standards. Thoughts?
http://www.w3.org/TR/2011/WD-contacts-api-20110616/#idl-def-ContactName

I would definately like to get the addContacts pulled in as well.
- I saw that in the future you would like to automatically ask for permission when someone calls getContacts.  I had done that originally, but found that if you make that call while anything is happening in the UI it will freeze and popup the ios Auth modal.  I made them deliberately separate so that this would not be the case.

**Comment by rt2zz** [comment]
1. Having the demo project intertwined with the library makes it hard to read the code as a user. Also it adds a lot of extra files & weight to the npm download. Perhaps the demo can go in an examples folder which is .npmignore'd ?
2. I realize this is a bit arbitrary, I think core even has an inconsistent api in a couple of placees :D 
3. Awesome

I had not known about the w3 contacts spec. Interesting, kinda being pulled between ios and web idioms a bit :/ 

I will make a couple of PR's for these, let me know your thoughts.

**Comment by mattotodd** [comment]
1 Ok, I understand the thoughts on the example.  That sounds fine (i didnt know about .npmignore thx)

About the w3 spec,  i'm not hung up either way,  and lastName FirstName makes more sense to me as an english speaking person,   whatever it may be,  I think it should be consistent across platforms (so If we go with one or the other, we use the same when react Android/Windows comes out).

I'll keep a lookout for the PRs   

thx

**Comment by rt2zz** [comment]
Thanks! I guess we can close this?

I will hopefully have a PR soon with react-native 0.4.\* compat

**Comment by mattotodd** [comment]
thank you much!
